### ISSUE TITLE
Nova is not working correctly with python-novaclient 10.2.0 or newer: add_resource_manager_extra_kwargs_hook deprecated

### ISSUE THREAD

**Issue by hkmaly** [rackerlabs/rackspace-novaclient#23]
When installing rackspace-novaclient with defalt (newest) dependencies, any nova command except help ends with
```
ERROR (AttributeError): 'module' object has no attribute 'add_resource_manager_extra_kwargs_hook'
```
The reason seems to be related to following note in https://docs.openstack.org/releasenotes/python-novaclient/rocky.html : _novaclient.utils.add_resource_manager_extra_kwargs_hook and novaclient.utils.get_resource_manager_extra_kwargs were designed for supporting extensions in nova/novaclient. Nowadays, this “extensions” feature is abandoned and both add_resource_manager_extra_kwargs_hook, add_resource_manager_extra_kwargs_hook are not used in novaclient’s code. These methods are not documented, so we are removing them without standard deprecation cycle._

Current version of python-novaclient is 14.0.0. The version 10.1.0 is working as expected.

No idea if you can workaround the kwargs_hook removal or if you would need to specify that python-novaclient version needs to be 10.1.0 or older in dependencies.

**Comment by fieldse** [comment]
Any updates on this?

**Comment by hkmaly** [comment]
I would like some answer as well.

**Comment by bdmorin** [comment]
Year later... Nova is still broke. Great job Rackspace.
